services:
  portfolio:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app/
    ports:
      - '8091:8091'
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_HOST = db

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=portfolio
